### ISSUE TITLE
How can i get the path of the <avatar>?

### ISSUE THREAD

**Issue by xiechunjie** [trunda/avatio-avatar#1]
hello! How can i get the path of the <avatar>? thanks

**Comment by xiechunjie** [comment]
i want to get the svg path or tans it to canvas

**Comment by trunda** [comment]
Hi there, I am very sorry for the late response. Look to the repository [avatio-server](https://github.com/trunda/avatio-server/blob/master/src/index.js#L89), where you can see, how to save the image to svg or png.
